# Generated by Django 2.2.5 on 2019-09-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('rated', models.CharField(max_length=10, null=True)),
                ('released', models.DateField(null=True)),
                ('runtime', models.CharField(max_length=10, null=True)),
                ('genre', models.CharField(max_length=120, null=True)),
                ('director', models.CharField(max_length=120, null=True)),
                ('writer', models.CharField(max_length=120, null=True)),
                ('actors', models.CharField(max_length=240, null=True)),
                ('plot', models.TextField(null=True)),
                ('language', models.CharField(max_length=120, null=True)),
                ('country', models.CharField(max_length=120, null=True)),
                ('awards', models.CharField(max_length=120, null=True)),
                ('poster', models.URLField(null=True)),
                ('metascore', models.IntegerField(null=True)),
                ('imdbrating', models.FloatField(null=True)),
                ('imdbvotes', models.IntegerField(null=True)),
                ('imdbid', models.CharField(max_length=120, null=True)),
                ('typee', models.CharField(max_length=120, null=True)),
                ('dvd', models.DateField(null=True)),
                ('boxoffice', models.CharField(max_length=120, null=True)),
                ('production', models.CharField(max_length=120, null=True)),
                ('website', models.URLField(null=True)),
                ('response', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=120, null=True)),
                ('value', models.CharField(max_length=120, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
            },
        ),
    ]
