# Generated by Django 2.2.5 on 2019-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='totalseasons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
