# Generated by Django 2.2.5 on 2019-09-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_totalseasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='boxoffice',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='typee',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='source',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
